name: CD

on:
  workflow_dispatch:
    inputs:
      bump_build_number:
        description: 'Bump the build number (false|true)'
        required: true
        default: 'true'
      tag_release:
        description: 'Tag commit and create the github release (false|true)'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: macOS-12

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          bundler: 'Gemfile.lock'
          bundler-cache: true

      - name: Create release
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          GIT_COMMITTER_NAME: Bot HLS Analyzer
          GIT_AUTHOR_NAME: Bot HLS Analyzer
          GIT_AUTHOR_EMAIL: bot@fabernovel.com
          GIT_COMMITTER_EMAIL: bot@fabernovel.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec fastlane hlsa_release \
          tag_release:${{ github.event.inputs.tag_release }} \
          bump_build_number:${{ github.event.inputs.bump_build_number }}
